### ISSUE TITLE
Update the Addon - Dynamic Latest Blog Posts section with the latest workflow

### ISSUE THREAD

**Issue by arafatiqbal** [rahuldkjain/github-profile-readme-generator#660]
**Is your feature request related to a problem? Please describe.**
I wanted to add the workflow to dynamically update with latest blog posts. I noticed the workflow code in the addon section was old. That old code doesn't have a few things like letting you run the workflow manually.

**Describe the solution you'd like**
I want to update the section for [dynamic latest blog posts](https://rahuldkjain.github.io/gh-profile-readme-generator/addons) to include the latest workflow code.

**Comment by arafatiqbal** [comment]
Old workflow code
```
name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://dev.to/feed/rahuldkjain, https://medium.com/feed/@rahuldkjain'
```
New workflow code
```
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/gautamkrishnar,https://www.gautamkrishnar.com/feed/"
```
